"""SSHClient — SSH tunnel + remote RAMIC daemon deployment.

Manages the SSH port-forward tunnel and remote file deployment independently
from the SKILL execution client (VirtuosoClient). VirtuosoClient only needs a
localhost:port TCP endpoint; SSHClient makes that endpoint available.
"""

from __future__ import annotations

import importlib.resources
import json
import logging
import os
import re
import signal
import socket
import subprocess
import time
from pathlib import Path
from typing import Any

from virtuoso_bridge.transport.remote_paths import default_virtuoso_bridge_dir, resolve_remote_username
from virtuoso_bridge.transport.ssh import SSHRunner, CommandResult

logger = logging.getLogger(__name__)

_TUNNEL_STARTUP_SETTLE_SECONDS = 1.0
_STATE_DIR = Path.home() / ".cache" / "virtuoso_bridge"
_STATE_FILE = _STATE_DIR / "state.json"


# ---------------------------------------------------------------------------
# Resource helpers (moved from bridge.py)
# ---------------------------------------------------------------------------

def _find_ramic_bridge_il() -> Path:
    try:
        resources = importlib.resources.files("virtuoso_bridge.virtuoso.basic.resources")
        il_ref = resources / "ramic_bridge.il"
        with importlib.resources.as_file(il_ref) as il_path:
            if il_path.is_file():
                return il_path
    except (ModuleNotFoundError, FileNotFoundError, TypeError):
        pass
    raise FileNotFoundError(
        "Cannot locate ramic_bridge.il in virtuoso_bridge.virtuoso.basic.resources."
    )


def _find_ramic_bridge_daemon(python_major: int) -> Path:
    filename = "ramic_bridge_daemon_3.py" if python_major >= 3 else "ramic_bridge_daemon_27.py"
    try:
        resources = importlib.resources.files("virtuoso_bridge.virtuoso.basic.resources")
        daemon_ref = resources / filename
        with importlib.resources.as_file(daemon_ref) as daemon_path:
            if daemon_path.is_file():
                return daemon_path
    except (ModuleNotFoundError, FileNotFoundError, TypeError):
        pass
    raise FileNotFoundError(f"Cannot locate {filename} in virtuoso_bridge.virtuoso.basic.resources.")


def _prepare_ramic_bridge_il(il_path: Path, port: int) -> str:
    content = il_path.read_text(encoding="utf-8")
    pattern = r"(RBPort\s*=\s*)\d+(\s*(;.*)?)$"
    def replace_port(match: re.Match[str]) -> str:
        comment = match.group(2) if match.group(2) else "  ; TCP port for client connections"
        return f"{match.group(1)}{port}{comment}"
    return re.sub(pattern, replace_port, content, flags=re.MULTILINE)


def _generate_virtuoso_setup_il(daemon_path: str, il_path: str, python_cmd: str = "python") -> str:
    return (
        "; Virtuoso CIW Setup Script - RAMIC Bridge\n"
        "; Auto-generated by virtuoso-bridge\n"
        f'; Execute in CIW: load("{il_path.replace(chr(0x5c), "/")}")\n'
        "\n"
        "; Set environment variables\n"
        f'setShellEnvVar("RB_DAEMON_PATH" "{daemon_path}")\n'
        f'setShellEnvVar("RB_PYTHON_PATH" "{python_cmd}")\n'
        "\n"
        "; Load RAMIC Bridge IL script\n"
        f'load("{il_path}")\n'
        "\n"
        "; Setup complete!\n"
    )


def _update_env_file(key: str, value: str) -> bool:
    here = Path.cwd()
    for parent in [here, *here.parents]:
        env_path = parent / ".env"
        if env_path.is_file():
            text = env_path.read_text(encoding="utf-8")
            new_text = re.sub(
                rf"^{re.escape(key)}\s*=.*$",
                f"{key}={value}",
                text,
                flags=re.MULTILINE,
            )
            if new_text != text:
                env_path.write_text(new_text, encoding="utf-8")
                logger.info("Updated %s=%s in %s", key, value, env_path)
                return True
            return False
    return False


# ---------------------------------------------------------------------------
# SSHClient
# ---------------------------------------------------------------------------

class SSHClient:
    """Manages SSH tunnel and remote RAMIC daemon deployment.

    Provides a localhost:port TCP endpoint that tunnels to the remote daemon.
    Completely independent of SKILL execution logic.
    """

    def __init__(
        self,
        remote_host: str,
        remote_user: str | None = None,
        port: int = 65432,
        jump_host: str | None = None,
        jump_user: str | None = None,
        timeout: int = 30,
        keep_remote_files: bool = False,
    ) -> None:
        self._remote_host = remote_host
        self._remote_user = remote_user
        self._port = port
        self._jump_host = jump_host
        self._jump_user = jump_user
        self._timeout = timeout
        self._keep_remote_files = keep_remote_files

        self._ssh_runner = SSHRunner(
            host=remote_host,
            user=remote_user,
            jump_host=jump_host,
            jump_user=jump_user,
            persistent_shell=True,
            verbose=True,
        )

        self._tunnel_proc: subprocess.Popen[bytes] | None = None
        self._saved_tunnel_pid: int | None = None
        self._using_external_tunnel = False
        self._remote_setup_done = False
        self._remote_work_dir: str | None = None
        self._remote_virtuoso_setup_path: str | None = None

    # -- factory methods ----------------------------------------------------

    @classmethod
    def from_env(cls, *, keep_remote_files: bool = False) -> "SSHClient":
        """Create from VB_* environment variables."""
        from dotenv import load_dotenv
        load_dotenv()

        remote_host = os.getenv("VB_REMOTE_HOST", "").strip()
        if not remote_host:
            raise RuntimeError("VB_REMOTE_HOST must be set")

        remote_user = os.getenv("VB_REMOTE_USER", "").strip() or None
        jump_host = os.getenv("VB_JUMP_HOST", "").strip() or None
        jump_user = os.getenv("VB_JUMP_USER", "").strip() or None

        # Port
        from virtuoso_bridge.virtuoso.basic.bridge import _default_remote_port
        try:
            port = int(os.getenv("VB_REMOTE_PORT", "").strip() or _default_remote_port(remote_user))
        except (ValueError, TypeError):
            port = _default_remote_port(remote_user)

        return cls(
            remote_host=remote_host,
            remote_user=remote_user,
            port=port,
            jump_host=jump_host,
            jump_user=jump_user,
            keep_remote_files=keep_remote_files,
        )

    # -- properties ---------------------------------------------------------

    @property
    def port(self) -> int:
        return self._port

    @property
    def remote_host(self) -> str:
        return self._remote_host

    @property
    def ssh_runner(self) -> SSHRunner:
        return self._ssh_runner

    @property
    def remote_work_dir(self) -> str | None:
        return self._remote_work_dir

    @property
    def setup_path(self) -> str | None:
        return self._remote_virtuoso_setup_path

    @property
    def is_tunnel_alive(self) -> bool:
        return self._tunnel_proc is not None and self._tunnel_proc.poll() is None

    # -- remote deployment --------------------------------------------------

    def _detect_remote_python(self) -> tuple[str, int]:
        detect_cmd = (
            'python3 --version 2>&1 && echo "CMD:python3" || '
            '(python --version 2>&1 && echo "CMD:python") || '
            '(python2.7 --version 2>&1 && echo "CMD:python2.7") || '
            'echo "CMD:NONE"'
        )
        result = self._ssh_runner.run_command(detect_cmd)
        output = result.stdout.strip()
        logger.info("Remote Python detection output: %s", output)

        python_cmd = None
        python_major = None
        for line in output.splitlines():
            line = line.strip()
            if line.startswith("CMD:"):
                cmd = line[4:]
                if cmd != "NONE":
                    python_cmd = cmd
            elif line.startswith("Python "):
                try:
                    python_major = int(line.split()[1].split(".")[0])
                except (IndexError, ValueError):
                    pass

        if python_cmd is None or python_major is None:
            raise RuntimeError(
                f"No Python interpreter found on {self._remote_host}. "
                f"Detection output: {output!r}"
            )
        logger.info("Detected remote Python: %s (major version %d)", python_cmd, python_major)
        return python_cmd, python_major

    def ensure_remote_setup(self) -> None:
        """Upload daemon files and generate virtuoso_setup.il on the remote host."""
        if self._remote_setup_done:
            return

        python_cmd, python_major = self._detect_remote_python()
        daemon_local = _find_ramic_bridge_daemon(python_major)
        il_local = _find_ramic_bridge_il()
        daemon_filename = daemon_local.name

        remote_username = resolve_remote_username(
            configured_user=self._remote_user,
            runner=self._ssh_runner,
        )
        self._remote_work_dir = default_virtuoso_bridge_dir(remote_username, "virtuoso_bridge")

        remote_daemon = f"{self._remote_work_dir}/{daemon_filename}"
        remote_il = f"{self._remote_work_dir}/ramic_bridge.il"
        remote_setup = f"{self._remote_work_dir}/virtuoso_setup.il"

        logger.info("Creating remote directory: %s", self._remote_work_dir)
        mkdir_result = self._ssh_runner.run_command(
            f"mkdir -p {self._remote_work_dir} && chmod 755 {self._remote_work_dir}"
        )
        if mkdir_result.returncode != 0:
            raise RuntimeError(f"Failed to create remote directory: {mkdir_result.stderr.strip()}")

        logger.info("Uploading daemon script (%s) to %s", daemon_filename, remote_daemon)
        daemon_content = daemon_local.read_text(encoding="utf-8")
        up = self._ssh_runner.upload_text(daemon_content, remote_daemon)
        if up.returncode != 0:
            raise RuntimeError(f"Failed to upload daemon: {up.stderr.strip()}")

        logger.info("Uploading IL script to %s", remote_il)
        il_content = _prepare_ramic_bridge_il(il_local, self._port)
        up = self._ssh_runner.upload_text(il_content, remote_il)
        if up.returncode != 0:
            raise RuntimeError(f"Failed to upload IL script: {up.stderr.strip()}")

        setup_content = _generate_virtuoso_setup_il(remote_daemon, remote_il, python_cmd)
        logger.info("Uploading setup script to %s", remote_setup)
        up = self._ssh_runner.upload_text(setup_content, remote_setup)
        if up.returncode != 0:
            raise RuntimeError(f"Failed to upload setup script: {up.stderr.strip()}")

        self._remote_setup_done = True
        self._remote_virtuoso_setup_path = remote_setup
        logger.info("Remote setup complete; setup script at %s (using %s)", remote_setup, python_cmd)

    # -- SSH tunnel ---------------------------------------------------------

    def _try_ssh_tunnel(self, port: int) -> subprocess.Popen[bytes] | None:
        cmd: list[str] = ["ssh"]
        cmd += [
            "-o", "BatchMode=yes",
            "-o", "StrictHostKeyChecking=no",
            "-o", "ExitOnForwardFailure=yes",
            "-N",
            "-L", f"{port}:127.0.0.1:{port}",
        ]
        if self._jump_host:
            jump_user = self._jump_user or self._remote_user
            jump_target = f"{jump_user}@{self._jump_host}" if jump_user else self._jump_host
            cmd += ["-J", jump_target]
        if self._remote_user:
            cmd.append(f"{self._remote_user}@{self._remote_host}")
        else:
            cmd.append(self._remote_host)

        logger.info("Starting SSH tunnel: %s", " ".join(cmd))
        print(f"[cmd] {' '.join(cmd)}", flush=True)

        # Platform-specific detach: tunnel must survive parent process exit
        if os.name == "nt":
            # On Windows, launching ssh.exe directly can still show a console
            # window, especially when ProxyJump causes ssh to spawn another ssh.
            # Start it from a hidden PowerShell process instead.
            pid = self._start_hidden_windows_process(cmd)

            settle = _TUNNEL_STARTUP_SETTLE_SECONDS
            if self._jump_host:
                settle = max(settle, 3.0)
            deadline = time.monotonic() + settle
            while time.monotonic() < deadline:
                if self._can_reach_port(port):
                    self._saved_tunnel_pid = pid
                    self._using_external_tunnel = True
                    return None
                time.sleep(0.1)

            try:
                os.kill(pid, signal.SIGTERM)
            except OSError:
                pass
            raise RuntimeError("SSH tunnel failed to start on Windows")
        else:
            popen_kwargs: dict[str, Any] = {
                "stdin": subprocess.DEVNULL,
                "stdout": subprocess.DEVNULL,
                "start_new_session": True,
                "stderr": subprocess.PIPE,
            }
            proc = subprocess.Popen(cmd, **popen_kwargs)

            # Wait for tunnel to settle (longer for jump-host paths)
            settle = _TUNNEL_STARTUP_SETTLE_SECONDS
            if self._jump_host:
                settle = max(settle, 3.0)
            deadline = time.monotonic() + settle
            while time.monotonic() < deadline:
                if proc.poll() is not None:
                    break
                time.sleep(0.1)

            if proc.poll() is not None:
                err_msg = ""
                if proc.stderr and proc.stderr.readable():
                    try:
                        err_msg = proc.stderr.read().decode("utf-8", errors="ignore")
                    except (OSError, ValueError):
                        pass
                if "address already in use" in err_msg.lower() and self._can_reach_port(port):
                    logger.info("Reusing existing tunnel at localhost:%d", port)
                    self._using_external_tunnel = True
                    return None
                return proc  # failed
            return proc  # running

    def _start_hidden_windows_process(self, cmd: list[str]) -> int:
        def _ps_quote(value: str) -> str:
            return "'" + value.replace("'", "''") + "'"

        file_path = _ps_quote(cmd[0])
        args = ", ".join(_ps_quote(part) for part in cmd[1:])
        script = (
            f"$p = Start-Process -FilePath {file_path} "
            f"-ArgumentList @({args}) -WindowStyle Hidden -PassThru; "
            "$p.Id"
        )
        result = subprocess.run(
            ["powershell.exe", "-NoProfile", "-NonInteractive", "-WindowStyle", "Hidden", "-Command", script],
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode != 0:
            raise RuntimeError(f"Failed to launch hidden SSH tunnel: {result.stderr.strip()}")
        try:
            return int(result.stdout.strip().splitlines()[-1])
        except (IndexError, ValueError) as exc:
            raise RuntimeError(
                f"Failed to parse hidden SSH tunnel PID: {result.stdout.strip()!r}"
            ) from exc

    def _can_reach_port(self, port: int) -> bool:
        """Check if localhost:port accepts TCP connections."""
        try:
            s = socket.create_connection(("127.0.0.1", port), timeout=2)
            s.close()
            return True
        except (ConnectionRefusedError, OSError):
            return False

    def ensure_tunnel(self) -> None:
        """Ensure SSH tunnel is running, auto-retry on port conflict."""
        if self._tunnel_proc is not None and self._tunnel_proc.poll() is None:
            return
        if self._using_external_tunnel and self._can_reach_port(self._port):
            return
        self._using_external_tunnel = False

        max_attempts = 10
        port = self._port
        for attempt in range(max_attempts):
            proc = self._try_ssh_tunnel(port)
            if proc is None:
                # Reusing existing tunnel
                self._port = port
                return
            if proc.poll() is None:
                # Tunnel running
                self._tunnel_proc = proc
                self._saved_tunnel_pid = proc.pid
                if port != self._port:
                    logger.info("Port %d was busy, using port %d", self._port, port)
                    print(f"[port] {self._port} busy, auto-switched to {port}", flush=True)
                    self._port = port
                    _update_env_file("VB_REMOTE_PORT", str(port))
                logger.info(
                    "SSH tunnel established (PID %d): localhost:%d -> %s:localhost:%d",
                    proc.pid, port, self._remote_host, port,
                )
                return
            # Failed
            stderr = proc.stderr
            err_msg = stderr.read().decode("utf-8", errors="ignore") if stderr else ""
            if "address already in use" in err_msg.lower() or "cannot listen" in err_msg.lower():
                logger.info("Port %d in use, trying %d", port, port + 1)
                port += 1
                continue
            raise RuntimeError(f"SSH tunnel failed: {err_msg.strip()}")

        raise RuntimeError(f"No free port found after {max_attempts} attempts ({self._port}–{port - 1})")

    # -- high-level lifecycle -----------------------------------------------

    def warm(self, timeout: int = 15) -> None:
        """Full startup: remote setup + persistent shell + tunnel."""
        self.ensure_remote_setup()
        if self._ssh_runner.persistent_shell_enabled:
            self._ssh_runner.ensure_persistent_shell(timeout=timeout)
        self.ensure_tunnel()
        self.save_state()

    def stop(self) -> None:
        """Kill the tunnel and clean up."""
        # Kill tunnel by PID (may be from state file or from this session)
        tunnel_pid = None
        if self._tunnel_proc is not None and self._tunnel_proc.poll() is None:
            tunnel_pid = self._tunnel_proc.pid
        elif not tunnel_pid:
            state = self.read_state()
            if state:
                tunnel_pid = state.get("tunnel_pid")

        if tunnel_pid:
            logger.info("Terminating SSH tunnel (PID %d)", tunnel_pid)
            try:
                os.kill(tunnel_pid, signal.SIGTERM)
            except OSError:
                pass
        self._tunnel_proc = None

        if not self._keep_remote_files and self._remote_setup_done and self._remote_work_dir:
            try:
                self._ssh_runner.run_command(f"rm -rf {self._remote_work_dir}")
            except Exception:
                logger.warning("Failed to clean up remote files at %s", self._remote_work_dir)

        try:
            self._ssh_runner.close()
        except Exception:
            pass

        # Clear state
        if _STATE_FILE.exists():
            _STATE_FILE.unlink(missing_ok=True)

    def close(self) -> None:
        """Close SSH runner without killing the tunnel (it survives for other scripts)."""
        try:
            self._ssh_runner.close()
        except Exception:
            pass

    # -- state file ---------------------------------------------------------

    def save_state(self) -> None:
        """Save tunnel state so other processes can find the port."""
        _STATE_DIR.mkdir(parents=True, exist_ok=True)
        tunnel_pid = self._tunnel_proc.pid if self._tunnel_proc and self._tunnel_proc.poll() is None else self._saved_tunnel_pid
        state = {
            "port": self._port,
            "tunnel_pid": tunnel_pid,
            "remote_host": self._remote_host,
            "setup_path": self._remote_virtuoso_setup_path,
            "started_at": time.time(),
        }
        _STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")

    @staticmethod
    def read_state() -> dict[str, Any] | None:
        """Read saved tunnel state."""
        if not _STATE_FILE.is_file():
            return None
        try:
            return json.loads(_STATE_FILE.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None

    @classmethod
    def is_running(cls) -> bool:
        """Check if a tunnel is running (port reachable or process alive)."""
        state = cls.read_state()
        if not state:
            return False
        port = state.get("port")
        pid = state.get("tunnel_pid")
        # Primary check: is the port reachable? (works on all platforms)
        if port:
            try:
                s = socket.create_connection(("127.0.0.1", port), timeout=1)
                s.close()
                return True
            except (ConnectionRefusedError, OSError):
                pass
        # Fallback: is the process alive? (os.kill(pid, 0) on Unix)
        if pid:
            try:
                os.kill(pid, 0)
                return True
            except (OSError, PermissionError):
                pass
        return False

    # -- file transfer (delegated to SSHRunner) -----------------------------

    def upload_file(self, local_path: Path, remote_path: str, timeout: int | None = None) -> CommandResult:
        return self._ssh_runner.upload(local_path, remote_path, timeout=timeout or self._timeout)

    def download_file(self, remote_path: str, local_path: Path, timeout: int | None = None, recursive: bool = False) -> CommandResult:
        return self._ssh_runner.download(remote_path, local_path, recursive=recursive, timeout=timeout or self._timeout)

    def upload_text(self, text: str, remote_path: str, timeout: int | None = None) -> CommandResult:
        return self._ssh_runner.upload_text(text, remote_path, timeout=timeout or self._timeout)

    def run_command(self, cmd: str, timeout: int | None = None) -> CommandResult:
        return self._ssh_runner.run_command(cmd, timeout=timeout or self._timeout)
