"""RAMICBridge – Python client for Virtuoso SKILL execution."""

from __future__ import annotations

import errno
import importlib.resources
import json
import logging
import os
import re
import shutil
import socket
import subprocess
import hashlib
import time
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

from virtuoso_bridge.virtuoso.basic.composition import compose_skill_script
from virtuoso_bridge.models import ExecutionStatus, VirtuosoInterface, VirtuosoResult
from virtuoso_bridge.virtuoso.ops import (
    close_current_cellview as op_close_current_cellview,
    default_view_type_for,
    escape_skill_string,
    open_cell_view as op_open_cell_view,
    open_window as op_open_window,
    save_current_cellview as op_save_current_cellview,
)
from virtuoso_bridge.virtuoso.layout import LayoutOps
from virtuoso_bridge.virtuoso.schematic import SchematicOps
from virtuoso_bridge.transport.remote_paths import default_virtuoso_bridge_dir, resolve_remote_username
from virtuoso_bridge.transport.ssh import SSHRunner

logger = logging.getLogger(__name__)

def _bridge_env(key: str, default: str = "") -> str:
    """Read a bridge environment variable from ``VB_*`` names only."""
    return os.getenv(key, default).strip()

def _default_remote_port(username: str | None = None) -> int:
    """Return a stable per-user default port in the range 65000–65499."""
    user = username or os.getenv("VB_REMOTE_USER", "").strip()
    if not user:
        return 65432
    return 65000 + (sum(ord(c) for c in user) % 500)

_STX = "\x02"
_NAK = "\x15"
_RECV_BUF_SIZE = 1024 * 1024
_TUNNEL_STARTUP_SETTLE_SECONDS = 1.0
_TUNNEL_CONNECT_RETRY_DELAY = 0.2
_TUNNEL_CONNECT_GRACE_SECONDS = 3.0

# ---------------------------------------------------------------------------
# Resource helpers
# ---------------------------------------------------------------------------

def _find_ramic_bridge_il() -> Path:
    """Locate the bundled RAMIC Bridge SKILL IL file."""
    try:
        resources = importlib.resources.files("virtuoso_bridge.virtuoso.basic.resources")
        il_ref = resources / "ramic_bridge.il"
        with importlib.resources.as_file(il_ref) as il_path:
            if il_path.is_file():
                return il_path
    except (ModuleNotFoundError, FileNotFoundError, TypeError):
        pass
    raise FileNotFoundError(
        "Cannot locate ramic_bridge.il in "
        "virtuoso_bridge.virtuoso.basic.resources. Reinstall the package."
    )


def _find_ramic_bridge_daemon(python_major: int) -> Path:
    """Locate the bundled RAMIC Bridge daemon script for the given Python major version."""
    filename = "ramic_bridge_daemon_3.py" if python_major >= 3 else "ramic_bridge_daemon_27.py"
    try:
        resources = importlib.resources.files("virtuoso_bridge.virtuoso.basic.resources")
        daemon_ref = resources / filename
        with importlib.resources.as_file(daemon_ref) as daemon_path:
            if daemon_path.is_file():
                return daemon_path
    except (ModuleNotFoundError, FileNotFoundError, TypeError):
        pass
    raise FileNotFoundError(
        f"Cannot locate {filename} in "
        "virtuoso_bridge.virtuoso.basic.resources. Reinstall the package."
    )


def _find_ramic_bridge_files() -> tuple[Path, Path]:
    """Locate the bundled RAMIC Bridge daemon script (Py2.7) and SKILL IL file.

    Kept for backward compatibility. New code should use
    ``_find_ramic_bridge_daemon`` + ``_find_ramic_bridge_il``.
    """
    return _find_ramic_bridge_daemon(2), _find_ramic_bridge_il()

def _prepare_ramic_bridge_il(il_path: Path, port: int) -> str:
    """Read ramic_bridge.il and replace RBPort with the specified port."""
    content = il_path.read_text(encoding="utf-8")
    pattern = r"(RBPort\s*=\s*)\d+(\s*(;.*)?)$"

    def replace_port(match: re.Match[str]) -> str:
        comment = match.group(2) if match.group(2) else "  ; TCP port for client connections"
        return f"{match.group(1)}{port}{comment}"

    return re.sub(pattern, replace_port, content, flags=re.MULTILINE)

def _generate_virtuoso_setup_il(daemon_path: str, il_path: str, python_cmd: str = "python") -> str:
    """Generate virtuoso_setup.il content for CIW loading."""
    return (
        "; Virtuoso CIW Setup Script - RAMIC Bridge\n"
        "; Auto-generated by virtuoso-bridge\n"
        f'; Execute in CIW: load("{il_path.replace(chr(0x5c), "/")}")\n'
        "\n"
        "; Set environment variables\n"
        f'setShellEnvVar("RB_DAEMON_PATH" "{daemon_path}")\n'
        f'setShellEnvVar("RB_PYTHON_PATH" "{python_cmd}")\n'
        "\n"
        "; Load RAMIC Bridge IL script\n"
        f'load("{il_path}")\n'
        "\n"
        "; Setup complete!\n"
    )

def _path_to_posix(path: str | Path) -> str:
    return Path(path).as_posix()

def _escape_skill_string(s: str) -> str:
    return escape_skill_string(s)

def _escape_for_skill_evalstring_source(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "")
        .replace("\n", "\\n")
    )

# ---------------------------------------------------------------------------
# RAMICBridge
# ---------------------------------------------------------------------------

class RAMICBridge(VirtuosoInterface):
    """Virtuoso SKILL bridge using the RAMIC daemon over TCP."""

    def __init__(
        self,
        remote: bool = False,
        host: str | None = None,
        port: int | None = None,
        timeout: int = 30,
        remote_host: str | None = None,
        remote_user: str | None = None,
        remote_work_dir: str | None = None,
        jump_host: str | None = None,
        jump_user: str | None = None,
        auto_setup: bool = True,
        keep_remote_files: bool = False,
        log_to_ciw: bool = True,
    ) -> None:
        self._remote_mode = remote

        if remote:
            self._host = "127.0.0.1"
            self._remote_host = _bridge_env("VB_REMOTE_HOST") or None
            self._remote_user = _bridge_env("VB_REMOTE_USER") or None
            try:
                self._port = int(os.getenv("VB_REMOTE_PORT", "").strip() or _default_remote_port(self._remote_user))
            except (ValueError, TypeError, AttributeError):
                self._port = _default_remote_port(self._remote_user)
            self._jump_host = _bridge_env("VB_JUMP_HOST") or None
            self._jump_user = _bridge_env("VB_JUMP_USER") or None
            self._remote_work_dir_user_provided = False
            self._remote_work_dir = None
        else:
            self._host = host or "127.0.0.1"
            try:
                self._port = port if port is not None else int(os.getenv("VB_REMOTE_PORT", "").strip() or _default_remote_port())
            except (ValueError, TypeError):
                self._port = _default_remote_port()
            self._remote_host = remote_host
            self._remote_user = remote_user
            self._remote_work_dir_user_provided = remote_work_dir is not None
            self._remote_work_dir = remote_work_dir
            self._jump_host = jump_host
            self._jump_user = jump_user

        self._timeout = timeout
        self._auto_setup = auto_setup
        self._keep_remote_files = keep_remote_files
        self._log_to_ciw = log_to_ciw
        self.layout = LayoutOps(self)
        self.schematic = SchematicOps(self)

        self._remote_setup_done = False
        self._remote_virtuoso_setup_path: str | None = None
        self._ssh_tunnel_proc: subprocess.Popen[bytes] | None = None
        self._using_external_tunnel = False
        self._ssh_runner: SSHRunner | None = None
        self._il_upload_cache: dict[str, tuple[str, str]] = {}  # path -> (md5, remote_path)

        if self._remote_host:
            self._ssh_runner = SSHRunner(
                host=self._remote_host,
                user=self._remote_user,
                jump_host=self._jump_host,
                jump_user=self._jump_user,
                persistent_shell=True,
                verbose=True,
            )

    # -- factory methods ----------------------------------------------------

    @classmethod
    def from_env(
        cls,
        *,
        timeout: int = 30,
        auto_setup: bool = True,
        keep_remote_files: bool = False,
        log_to_ciw: bool = True,
    ) -> "RAMICBridge":
        """Create a remote bridge from environment variables / .env file."""
        load_dotenv()
        return cls(
            remote=True,
            timeout=timeout,
            auto_setup=auto_setup,
            keep_remote_files=keep_remote_files,
            log_to_ciw=log_to_ciw,
        )

    @classmethod
    def local(
        cls,
        host: str = "127.0.0.1",
        port: int = 65432,
        timeout: int = 30,
    ) -> "RAMICBridge":
        """Create a bridge for a locally running daemon."""
        return cls(remote=False, host=host, port=port, timeout=timeout)

    # -- context manager ----------------------------------------------------

    def __enter__(self) -> "RAMICBridge":
        return self

    def __exit__(self, *_: Any) -> None:
        self.close()

    # -- properties ---------------------------------------------------------

    @property
    def host(self) -> str:
        """Daemon host address."""
        return self._host

    @property
    def port(self) -> int:
        """Daemon TCP port."""
        return self._port

    @property
    def remote_host(self) -> str | None:
        """Remote server address (``None`` for local mode)."""
        return self._remote_host

    @property
    def is_remote(self) -> bool:
        """Whether the bridge is configured for remote deployment."""
        return self._remote_mode or (self._remote_host is not None)

    @property
    def is_tunnel_alive(self) -> bool:
        """Whether the SSH tunnel process is currently running."""
        return self._ssh_tunnel_proc is not None and self._ssh_tunnel_proc.poll() is None

    @property
    def log_to_ciw(self) -> bool:
        """Whether load_il / ciw_log print RAMIC lines to CIW."""
        return self._log_to_ciw

    @log_to_ciw.setter
    def log_to_ciw(self, value: bool) -> None:
        self._log_to_ciw = bool(value)

    # -- VirtuosoInterface --------------------------------------------------

    def ensure_ready(self, timeout: int = 10) -> VirtuosoResult:
        """Ensure the bridge is ready: remote setup, tunnel, and daemon reachable."""
        metadata: dict[str, Any] = {}
        errors: list[str] = []

        if self._remote_mode and not (self._remote_host and self._remote_host.strip()):
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=["VB_REMOTE_HOST must be set and non-empty when remote=True"],
                metadata={"remote": True},
            )

        if self._remote_host and self._auto_setup and not self._remote_setup_done:
            try:
                self.ensure_remote_setup()
                metadata["remote_setup_done"] = True
            except Exception as e:  # noqa: BLE001
                logger.warning("Remote setup failed: %s", e)
                errors.append(f"Remote setup failed: {e}")
                metadata["remote_setup_error"] = str(e)
                return VirtuosoResult(
                    status=ExecutionStatus.ERROR, errors=errors, metadata=metadata
                )

        if self._remote_host:
            try:
                self.ensure_ssh_tunnel()
                metadata["tunnel_alive"] = self.is_tunnel_alive
            except Exception as e:  # noqa: BLE001
                logger.warning("SSH tunnel failed: %s", e)
                errors.append(f"SSH tunnel failed: {e}")
                metadata["tunnel_error"] = str(e)
                metadata["tunnel_alive"] = False
                return VirtuosoResult(
                    status=ExecutionStatus.ERROR, errors=errors, metadata=metadata
                )

        report = self.verify_tunnel(timeout=timeout)
        metadata["diagnostics"] = report
        if not report["tcp_reachable"]:
            errors.append("TCP connection to daemon host:port failed")
        if not report["daemon_responsive"]:
            errors.append("Daemon did not respond to ping (ensure load() in CIW)")

        if errors:
            if self._remote_virtuoso_setup_path and not report.get("daemon_responsive", False):
                print(
                    "\nPlease execute in Virtuoso CIW: "
                    f'load("{self._remote_virtuoso_setup_path}")\n'
                )
            return VirtuosoResult(
                status=ExecutionStatus.ERROR, errors=errors, metadata=metadata
            )
        return VirtuosoResult(status=ExecutionStatus.SUCCESS, metadata=metadata)

    def warm_remote_session(self, timeout: int = 10) -> VirtuosoResult:
        """Warm up remote transports without requiring the daemon to answer."""
        metadata: dict[str, Any] = {}
        errors: list[str] = []

        if self._remote_mode and not (self._remote_host and self._remote_host.strip()):
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=["VB_REMOTE_HOST must be set and non-empty when remote=True"],
                metadata={"remote": True},
            )

        if self._remote_host and self._auto_setup and not self._remote_setup_done:
            try:
                self.ensure_remote_setup()
                metadata["remote_setup_done"] = True
            except Exception as e:  # noqa: BLE001
                errors.append(f"Remote setup failed: {e}")
                metadata["remote_setup_error"] = str(e)
                return VirtuosoResult(
                    status=ExecutionStatus.ERROR, errors=errors, metadata=metadata
                )

        if self._ssh_runner is not None and self._ssh_runner.persistent_shell_enabled:
            try:
                self._ssh_runner.ensure_persistent_shell(timeout=timeout)
                metadata["persistent_shell_ready"] = True
            except Exception as e:  # noqa: BLE001
                errors.append(f"Persistent SSH shell failed: {e}")
                metadata["persistent_shell_error"] = str(e)
                return VirtuosoResult(
                    status=ExecutionStatus.ERROR, errors=errors, metadata=metadata
                )

        if self._remote_host:
            try:
                self.ensure_ssh_tunnel()
                metadata["tunnel_alive"] = self.is_tunnel_alive
            except Exception as e:  # noqa: BLE001
                errors.append(f"SSH tunnel failed: {e}")
                metadata["tunnel_error"] = str(e)
                metadata["tunnel_alive"] = False
                return VirtuosoResult(
                    status=ExecutionStatus.ERROR, errors=errors, metadata=metadata
                )

        return VirtuosoResult(status=ExecutionStatus.SUCCESS, metadata=metadata)

    def load_il(self, path: str | Path, timeout: int | None = None) -> VirtuosoResult:
        """Load an IL file in Virtuoso."""
        try:
            prepared, uploaded = self._prepare_il_path(path)
        except Exception as e:  # noqa: BLE001
            logger.warning("Path preparation failed for %s: %s", path, e)
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Path preparation failed: {e}"],
                metadata={"path": str(path)},
            )
        effective_timeout = timeout if timeout is not None else self._timeout
        pe = _escape_skill_string(prepared)
        if self._log_to_ciw:
            skill_code = (
                f"prog((rbLret rbMsg) "
                f'printf("%s\\n" strcat("RAMIC load_il >> " "{pe}")) '
                f'rbLret = load("{pe}") '
                f'rbMsg = if(stringp(rbLret) then rbLret else sprintf(nil "%L" rbLret)) '
                f'printf("%s\\n" strcat("RAMIC load_il << " rbMsg)) '
                f"return(rbLret))"
            )
        else:
            skill_code = f'load("{pe}")'
        result = self.execute_skill(skill_code, timeout=effective_timeout)
        result.metadata["skill_command"] = f'load("{prepared}")'
        result.metadata["uploaded"] = uploaded
        return result

    def open_cell_view(
        self,
        lib: str,
        cell: str,
        *,
        view: str = "layout",
        view_type: str | None = None,
        mode: str = "w",
        timeout: int | None = None,
    ) -> VirtuosoResult:
        """Open a target cellview and bind it to ``cv`` in Virtuoso."""
        effective_timeout = timeout if timeout is not None else self._timeout
        resolved_view_type = view_type or default_view_type_for(view)
        skill_code = op_open_cell_view(
            lib,
            cell,
            view=view,
            view_type=resolved_view_type,
            mode=mode,
        )
        result = self.execute_skill(skill_code, timeout=effective_timeout)
        if result.status != ExecutionStatus.SUCCESS:
            return result
        if (result.output or "").strip().lower() == "nil":
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Failed to open cellview {lib}/{cell}/{view}"],
                metadata={
                    "lib": lib,
                    "cell": cell,
                    "view": view,
                    "view_type": resolved_view_type,
                    "mode": mode,
                },
                execution_time=result.execution_time,
            )
        return result

    def open_window(
        self,
        lib: str,
        cell: str,
        *,
        view: str = "layout",
        view_type: str | None = None,
        mode: str = "a",
        timeout: int | None = None,
    ) -> VirtuosoResult:
        """Open a Virtuoso window for a target cellview."""
        effective_timeout = timeout if timeout is not None else self._timeout
        resolved_view_type = view_type or default_view_type_for(view)
        skill_code = op_open_window(
            lib,
            cell,
            view=view,
            view_type=resolved_view_type,
            mode=mode,
        )
        result = self.execute_skill(skill_code, timeout=effective_timeout)
        if result.status != ExecutionStatus.SUCCESS:
            return result
        if (result.output or "").strip().lower() == "nil":
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Failed to open window for {lib}/{cell}/{view}"],
                metadata={
                    "lib": lib,
                    "cell": cell,
                    "view": view,
                    "view_type": resolved_view_type,
                    "mode": mode,
                },
                execution_time=result.execution_time,
            )
        return result

    def ciw_print(self, message: str, timeout: int | None = None) -> VirtuosoResult:
        """Print a message to the Virtuoso CIW."""
        effective_timeout = timeout if timeout is not None else self._timeout
        escaped = _escape_skill_string(message)
        return self.execute_skill(
            f'progn(printf("%s\\n" "{escaped}") t)',
            timeout=effective_timeout,
        )

    def ciw_log(self, skill_code: str, timeout: int | None = None) -> VirtuosoResult:
        """Execute SKILL code and print command + result to CIW."""
        effective_timeout = timeout if timeout is not None else self._timeout
        code = skill_code.strip()
        if not self._log_to_ciw:
            return self.execute_skill(code, timeout=effective_timeout)
        esc_eval = _escape_for_skill_evalstring_source(code)
        esc_display = _escape_skill_string(code)
        wrapped = (
            f"prog((rbRret rbMsg) "
            f'printf("%s\\n" strcat("RAMIC >> " "{esc_display}")) '
            f'rbRret = evalstring("{esc_eval}") '
            f'rbMsg = if(stringp(rbRret) then rbRret else sprintf(nil "%L" rbRret)) '
            f'printf("%s\\n" strcat("RAMIC << " rbMsg)) '
            f"return(rbRret))"
        )
        return self.execute_skill(wrapped, timeout=effective_timeout)

    def save_current_cellview(self, timeout: int | None = None) -> VirtuosoResult:
        """Save the current edit cellview, falling back to bound ``cv`` when present."""
        effective_timeout = timeout if timeout is not None else self._timeout
        skill_code = op_save_current_cellview()
        result = self.execute_skill(skill_code, timeout=effective_timeout)
        if result.status != ExecutionStatus.SUCCESS:
            return result
        if (result.output or "").strip().lower() == "nil":
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=["No active cellview available to save"],
                execution_time=result.execution_time,
            )
        return result

    def close_current_cellview(self, timeout: int | None = None) -> VirtuosoResult:
        """Close the current edit cellview, falling back to bound ``cv`` when present."""
        effective_timeout = timeout if timeout is not None else self._timeout
        skill_code = op_close_current_cellview()
        result = self.execute_skill(skill_code, timeout=effective_timeout)
        if result.status != ExecutionStatus.SUCCESS:
            return result
        if (result.output or "").strip().lower() == "nil":
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=["No active cellview available to close"],
                execution_time=result.execution_time,
            )
        return result

    def get_current_design(
        self, timeout: int | None = None
    ) -> tuple[str | None, str | None, str | None]:
        """Return ``(lib, cell, view)`` for the active edit cellview."""
        effective_timeout = timeout if timeout is not None else self._timeout
        skill = (
            'sprintf(nil "%s" '
            "ddGetObjReadPath(dbGetCellViewDdId(geGetEditCellView())))"
        )
        result = self.execute_skill(skill, timeout=effective_timeout)
        if result.status != ExecutionStatus.SUCCESS:
            return None, None, None
        output = (result.output or "").strip()
        if not output or output.lower() == "nil":
            return None, None, None
        parts = output.split("/")
        if len(parts) < 4:
            return None, None, None
        return parts[-4], parts[-3], parts[-2]

    def run_shell_command(
        self, cmd: str, timeout: int | None = None
    ) -> VirtuosoResult:
        """Run a shell command on the Virtuoso host via SKILL's ``csh()`` function."""
        effective_timeout = timeout if timeout is not None else self._timeout
        escaped = _escape_skill_string(cmd)
        result = self.execute_skill(f'csh("{escaped}")', timeout=effective_timeout)
        if result.status != ExecutionStatus.SUCCESS:
            return result
        if (result.output or "").strip().lower() == "nil":
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Shell command failed (csh returned nil): {cmd}"],
                metadata={"cmd": cmd},
                execution_time=result.execution_time,
            )
        return result

    def download_file(
        self,
        remote_path: str | Path,
        local_path: str | Path,
        *,
        timeout: int | None = None,
    ) -> VirtuosoResult:
        """Download a file from the Virtuoso host to a local path."""
        started = time.perf_counter()
        source = _path_to_posix(remote_path)
        destination = Path(local_path)
        destination.parent.mkdir(parents=True, exist_ok=True)

        if self._remote_host and self._ssh_runner is not None:
            effective_timeout = timeout if timeout is not None else self._timeout
            result = self._ssh_runner.download(source, destination, timeout=effective_timeout)
            elapsed = time.perf_counter() - started
            if result.returncode != 0:
                return VirtuosoResult(
                    status=ExecutionStatus.ERROR,
                    errors=[result.stderr.strip() or result.stdout.strip() or f"Failed to download {source}"],
                    execution_time=elapsed,
                    metadata={"remote_path": source, "local_path": str(destination)},
                )
            return VirtuosoResult(
                status=ExecutionStatus.SUCCESS,
                output=str(destination),
                execution_time=elapsed,
                metadata={"remote_path": source, "local_path": str(destination)},
            )

        try:
            shutil.copy2(Path(source), destination)
        except OSError as exc:
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Failed to copy local file {source}: {exc}"],
                execution_time=time.perf_counter() - started,
                metadata={"remote_path": source, "local_path": str(destination)},
            )
        return VirtuosoResult(
            status=ExecutionStatus.SUCCESS,
            output=str(destination),
            execution_time=time.perf_counter() - started,
            metadata={"remote_path": source, "local_path": str(destination)},
        )

    def upload_file(
        self,
        local_path: str | Path,
        remote_path: str | Path,
        *,
        timeout: int | None = None,
    ) -> VirtuosoResult:
        """Upload a local file to the Virtuoso host path."""
        started = time.perf_counter()
        source = Path(local_path)
        destination = _path_to_posix(remote_path)

        if not source.exists():
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Local file not found: {source}"],
                execution_time=time.perf_counter() - started,
                metadata={"local_path": str(source), "remote_path": destination},
            )

        if self._remote_host and self._ssh_runner is not None:
            effective_timeout = timeout if timeout is not None else self._timeout
            result = self._ssh_runner.upload(source, destination, timeout=effective_timeout)
            elapsed = time.perf_counter() - started
            if result.returncode != 0:
                return VirtuosoResult(
                    status=ExecutionStatus.ERROR,
                    errors=[
                        result.stderr.strip()
                        or result.stdout.strip()
                        or f"Failed to upload {source} to {destination}"
                    ],
                    execution_time=elapsed,
                    metadata={"local_path": str(source), "remote_path": destination},
                )
            return VirtuosoResult(
                status=ExecutionStatus.SUCCESS,
                output=destination,
                execution_time=elapsed,
                metadata={"local_path": str(source), "remote_path": destination},
            )

        try:
            target = Path(destination)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        except OSError as exc:
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Failed to copy local file {source} to {destination}: {exc}"],
                execution_time=time.perf_counter() - started,
                metadata={"local_path": str(source), "remote_path": destination},
            )
        return VirtuosoResult(
            status=ExecutionStatus.SUCCESS,
            output=destination,
            execution_time=time.perf_counter() - started,
            metadata={"local_path": str(source), "remote_path": destination},
        )
        return VirtuosoResult(
            status=ExecutionStatus.SUCCESS,
            output=str(destination),
            execution_time=time.perf_counter() - started,
            metadata={"remote_path": source, "local_path": str(destination)},
        )

    def run_il_file(
        self,
        path: str | Path,
        lib: str,
        cell: str,
        *,
        view: str = "layout",
        view_type: str | None = None,
        mode: str = "w",
        open_window: bool = True,
        save: bool = False,
        timeout: int | None = None,
    ) -> VirtuosoResult:
        """Open a target cellview, load an IL file, and optionally save the result."""
        effective_timeout = timeout if timeout is not None else self._timeout

        opened = self.open_cell_view(
            lib,
            cell,
            view=view,
            view_type=view_type,
            mode=mode,
            timeout=effective_timeout,
        )
        if opened.status != ExecutionStatus.SUCCESS:
            return opened

        if open_window:
            window_result = self.open_window(
                lib,
                cell,
                view=view,
                view_type=view_type,
                timeout=effective_timeout,
            )
            if window_result.status != ExecutionStatus.SUCCESS:
                return window_result

        sync_result = self.execute_skill("cv = geGetEditCellView()", timeout=effective_timeout)
        if sync_result.status != ExecutionStatus.SUCCESS:
            return sync_result

        load_result = self.load_il(path, timeout=effective_timeout)
        if load_result.status != ExecutionStatus.SUCCESS or not save:
            return load_result

        save_result = self.save_current_cellview(timeout=effective_timeout)
        if save_result.status != ExecutionStatus.SUCCESS:
            save_result.metadata["load_result"] = load_result.model_dump(mode="json")
            return save_result

        save_result.metadata["load_result"] = load_result.model_dump(mode="json")
        return save_result

    def execute_operations(
        self,
        commands: list[str],
        *,
        timeout: int | None = None,
        wrap_in_progn: bool = True,
    ) -> VirtuosoResult:
        """Compose and execute a batch of atomic SKILL operations."""
        effective_timeout = timeout if timeout is not None else self._timeout
        try:
            script = compose_skill_script(commands, wrap_in_progn=wrap_in_progn)
        except ValueError as exc:
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[str(exc)],
            )
        result = self.execute_skill(script, timeout=effective_timeout)
        result.metadata.setdefault("operation_count", len([cmd for cmd in commands if cmd and cmd.strip()]))
        return result

    def execute_skill(self, skill_code: str, timeout: int | None = None) -> VirtuosoResult:
        """Execute SKILL code in Virtuoso via the RAMIC Bridge daemon."""
        effective_timeout = timeout if timeout is not None else self._timeout

        if self._remote_host and self._auto_setup and not self._remote_setup_done:
            self.ensure_remote_setup()

        if self._remote_host:
            self.ensure_ssh_tunnel()

        start_time = time.monotonic()
        connect_deadline = start_time
        if self._jump_host:
            connect_deadline = start_time + _TUNNEL_CONNECT_GRACE_SECONDS

        try:
            while True:
                try:
                    raw_response = self._execute_skill_once(skill_code, effective_timeout)
                    elapsed = time.monotonic() - start_time
                    return self._parse_response(raw_response, elapsed)
                except ConnectionRefusedError:
                    now = time.monotonic()
                    if now >= connect_deadline:
                        raise
                    time.sleep(_TUNNEL_CONNECT_RETRY_DELAY)
                except OSError as exc:
                    if not self._should_retry_tunnel_connect(exc, time.monotonic(), connect_deadline):
                        raise
                    time.sleep(_TUNNEL_CONNECT_RETRY_DELAY)

        except socket.timeout:
            elapsed = time.monotonic() - start_time
            logger.error("SKILL execution timed out after %.1fs", elapsed)
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Socket timeout after {effective_timeout}s"],
                execution_time=elapsed,
            )
        except ConnectionRefusedError:
            elapsed = time.monotonic() - start_time
            logger.error("Connection refused to %s:%d", self._host, self._port)
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[
                    f"Connection refused to {self._host}:{self._port}. "
                    "Ensure the RAMIC Bridge daemon is running in Virtuoso."
                ],
                execution_time=elapsed,
            )
        except OSError as exc:
            elapsed = time.monotonic() - start_time
            logger.error("Socket error: %s", exc)
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[f"Socket error: {exc}"],
                execution_time=elapsed,
            )

    def test_connection(self, timeout: int = 10) -> bool:
        """Test whether the daemon is reachable by executing ``1+1``."""
        result = self.execute_skill("1+1", timeout=timeout)
        return result.status == ExecutionStatus.SUCCESS

    def verify_tunnel(self, timeout: int = 5) -> dict[str, Any]:
        """Diagnose the SSH tunnel and daemon connectivity."""
        report: dict[str, Any] = {
            "tunnel_process_alive": None,
            "tcp_reachable": False,
            "daemon_responsive": False,
            "daemon_output": "",
            "summary": "",
        }

        if self._ssh_tunnel_proc is not None:
            report["tunnel_process_alive"] = self.is_tunnel_alive

        result = self.execute_skill("1+1", timeout=timeout)
        report["daemon_responsive"] = result.status == ExecutionStatus.SUCCESS
        report["daemon_output"] = result.output
        report["tcp_reachable"] = not any(
            err.startswith("Connection refused to ") or err.startswith("Socket error:")
            for err in result.errors
        )

        parts: list[str] = []
        if report["tunnel_process_alive"] is True:
            parts.append("tunnel: alive")
        elif report["tunnel_process_alive"] is False:
            parts.append("tunnel: DEAD")
        else:
            parts.append("tunnel: not managed (manual or local)")
        parts.append(
            f"tcp {self._host}:{self._port}: "
            + ("OK" if report["tcp_reachable"] else "UNREACHABLE")
        )
        parts.append("daemon: " + ("OK" if report["daemon_responsive"] else "NO RESPONSE"))
        report["summary"] = " | ".join(parts)

        return report

    # -- remote deployment --------------------------------------------------

    def _detect_remote_python(self) -> tuple[str, int]:
        """Detect the best available Python interpreter on the remote host.

        Returns (python_command, major_version).  Tries python3 first, then
        python, then python2.7.  Raises RuntimeError if nothing is found.
        """
        if self._ssh_runner is None:
            raise RuntimeError("Cannot detect remote Python without a remote_host.")

        # Single compound command to minimize SSH round-trips
        detect_cmd = (
            'python3 --version 2>&1 && echo "CMD:python3" || '
            '(python --version 2>&1 && echo "CMD:python") || '
            '(python2.7 --version 2>&1 && echo "CMD:python2.7") || '
            'echo "CMD:NONE"'
        )
        result = self._ssh_runner.run_command(detect_cmd)
        output = result.stdout.strip()

        logger.info("Remote Python detection output: %s", output)

        # Parse output: look for "Python X.Y.Z" and the CMD: marker
        python_cmd = None
        python_major = None
        for line in output.splitlines():
            line = line.strip()
            if line.startswith("CMD:"):
                cmd = line[4:]
                if cmd != "NONE":
                    python_cmd = cmd
            elif line.startswith("Python "):
                try:
                    python_major = int(line.split()[1].split(".")[0])
                except (IndexError, ValueError):
                    pass

        if python_cmd is None or python_major is None:
            raise RuntimeError(
                f"No Python interpreter found on {self._remote_host}. "
                f"Detection output: {output!r}"
            )

        logger.info("Detected remote Python: %s (major version %d)", python_cmd, python_major)
        return python_cmd, python_major

    def ensure_remote_setup(self) -> None:
        """Upload daemon files and generate ``virtuoso_setup.il`` on the remote host."""
        if self._remote_setup_done:
            return

        if self._ssh_runner is None:
            raise RuntimeError("Cannot perform remote setup without a remote_host.")

        # Detect remote Python version first
        python_cmd, python_major = self._detect_remote_python()

        daemon_local = _find_ramic_bridge_daemon(python_major)
        il_local = _find_ramic_bridge_il()
        daemon_filename = daemon_local.name

        if not getattr(self, "_remote_work_dir_user_provided", False):
            remote_username = resolve_remote_username(
                configured_user=self._remote_user,
                runner=self._ssh_runner,
            )
            self._remote_work_dir = default_virtuoso_bridge_dir(
                remote_username, "virtuoso_bridge"
            )

        remote_daemon = f"{self._remote_work_dir}/{daemon_filename}"
        remote_il = f"{self._remote_work_dir}/ramic_bridge.il"
        remote_setup = f"{self._remote_work_dir}/virtuoso_setup.il"

        logger.info("Creating remote directory: %s", self._remote_work_dir)
        mkdir_result = self._ssh_runner.run_command(
            f"mkdir -p {self._remote_work_dir} && chmod 755 {self._remote_work_dir}"
        )
        if mkdir_result.returncode != 0:
            raise RuntimeError(
                self._ssh_runner.describe_ssh_command_failure(
                    "create the remote bridge directory",
                    mkdir_result,
                )
            )

        logger.info("Uploading daemon script (%s) to %s", daemon_filename, remote_daemon)
        daemon_content = daemon_local.read_text(encoding="utf-8")
        up_daemon = self._ssh_runner.upload_text(daemon_content, remote_daemon)
        if up_daemon.returncode != 0:
            raise RuntimeError(
                self._ssh_runner.describe_ssh_command_failure(
                    "upload the RAMIC daemon script",
                    up_daemon,
                )
            )

        logger.info("Uploading IL script to %s", remote_il)
        il_content = _prepare_ramic_bridge_il(il_local, self._port)
        up_il = self._ssh_runner.upload_text(il_content, remote_il)
        if up_il.returncode != 0:
            raise RuntimeError(
                self._ssh_runner.describe_ssh_command_failure(
                    "upload the RAMIC IL script",
                    up_il,
                )
            )

        setup_content = _generate_virtuoso_setup_il(remote_daemon, remote_il, python_cmd)
        logger.info("Uploading setup script to %s", remote_setup)
        up_setup = self._ssh_runner.upload_text(setup_content, remote_setup)
        if up_setup.returncode != 0:
            raise RuntimeError(
                self._ssh_runner.describe_ssh_command_failure(
                    "upload the Virtuoso setup script",
                    up_setup,
                )
            )

        self._remote_setup_done = True
        self._remote_virtuoso_setup_path = remote_setup
        logger.info("Remote setup complete; setup script at %s (using %s)", remote_setup, python_cmd)

    # -- SSH tunnel ---------------------------------------------------------

    def ensure_ssh_tunnel(self) -> None:
        """Ensure an SSH port-forward tunnel is running."""
        if self._ssh_tunnel_proc is not None and self._ssh_tunnel_proc.poll() is None:
            return
        if self._using_external_tunnel:
            if self._can_reuse_existing_tunnel():
                return
            self._using_external_tunnel = False
        if not self._remote_host:
            return

        cmd: list[str] = ["ssh"]
        cmd += [
            "-o", "BatchMode=yes",
            "-o", "StrictHostKeyChecking=no",
            "-o", "ExitOnForwardFailure=yes",
            "-N",
            "-L", f"{self._port}:localhost:{self._port}",
        ]
        if self._jump_host:
            jump_user = self._jump_user or self._remote_user
            jump_target = (
                f"{jump_user}@{self._jump_host}"
                if jump_user
                else self._jump_host
            )
            cmd += ["-J", jump_target]
        if self._remote_user:
            cmd.append(f"{self._remote_user}@{self._remote_host}")
        else:
            cmd.append(self._remote_host)

        logger.info("Starting SSH tunnel: %s", " ".join(cmd))
        print(f"[cmd] {' '.join(cmd)}", flush=True)
        self._ssh_tunnel_proc = subprocess.Popen(
            cmd,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )

        startup_deadline = time.monotonic() + _TUNNEL_STARTUP_SETTLE_SECONDS
        while time.monotonic() < startup_deadline:
            if self._ssh_tunnel_proc.poll() is not None:
                break
            time.sleep(0.05)

        if self._ssh_tunnel_proc.poll() is not None:
            stderr = self._ssh_tunnel_proc.stderr
            err_msg = stderr.read().decode("utf-8", errors="ignore") if stderr else ""
            if self._should_reuse_existing_tunnel(err_msg):
                logger.info(
                    "Reusing existing local tunnel/daemon path at %s:%d",
                    self._host,
                    self._port,
                )
                self._ssh_tunnel_proc = None
                self._using_external_tunnel = True
                return
            logger.error("SSH tunnel exited immediately: %s", err_msg)
            details = self._ssh_runner._summarize_ssh_transport_error(err_msg) if self._ssh_runner else err_msg
            raise RuntimeError(f"SSH tunnel failed to start: {details}")

        logger.info(
            "SSH tunnel established (PID %d): localhost:%d -> %s:localhost:%d",
            self._ssh_tunnel_proc.pid,
            self._port,
            self._remote_host,
            self._port,
        )

    def _execute_skill_once(self, skill_code: str, effective_timeout: int) -> str:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.settimeout(effective_timeout)
            sock.connect((self._host, self._port))
            request_data = {"skill": skill_code, "timeout": effective_timeout}
            sock.sendall(json.dumps(request_data).encode("utf-8"))
            sock.shutdown(socket.SHUT_WR)
            chunks: list[bytes] = []
            while True:
                chunk = sock.recv(_RECV_BUF_SIZE)
                if not chunk:
                    break
                chunks.append(chunk)
            return b"".join(chunks).decode("utf-8", errors="ignore")

    @staticmethod
    def _should_retry_tunnel_connect(
        exc: OSError,
        now: float,
        connect_deadline: float,
    ) -> bool:
        if now >= connect_deadline:
            return False
        retryable_errno = {
            getattr(errno, "ECONNREFUSED", 111),
            getattr(errno, "ECONNRESET", 104),
            getattr(errno, "ENOTCONN", 57),
        }
        err_no = getattr(exc, "errno", None)
        if err_no in retryable_errno:
            return True
        return "Connection refused" in str(exc)

    def _should_reuse_existing_tunnel(self, err_msg: str) -> bool:
        if "address already in use" not in err_msg.lower():
            return False
        return self._can_reuse_existing_tunnel()

    def _can_reuse_existing_tunnel(self) -> bool:
        try:
            raw_response = self._execute_skill_once("1+1", min(5, self._timeout))
        except (ConnectionRefusedError, OSError, socket.timeout):
            return False
        result = self._parse_response(raw_response, elapsed=0.0)
        return result.status == ExecutionStatus.SUCCESS

    # -- cleanup ------------------------------------------------------------

    def close(self) -> None:
        """Shut down the SSH tunnel and clean up remote files."""
        self._kill_tunnel()
        if (
            self._remote_host
            and not self._keep_remote_files
            and self._remote_setup_done
            and self._ssh_runner
        ):
            logger.info("Cleaning up remote files in %s", self._remote_work_dir)
            try:
                self._ssh_runner.run_command(f"rm -rf {self._remote_work_dir}")
            except Exception:  # noqa: BLE001
                logger.warning("Failed to clean up remote files at %s", self._remote_work_dir)
        if self._ssh_runner is not None:
            try:
                self._ssh_runner.close()
            except Exception:  # noqa: BLE001
                logger.warning("Failed to close SSH runner for %s", self._remote_host)

    def __del__(self) -> None:
        try:
            self.close()
        except Exception:  # noqa: BLE001
            pass

    # -- private helpers ----------------------------------------------------

    def _prepare_il_path(self, path: str | Path) -> tuple[str, bool]:
        """Return (remote_path, uploaded) where uploaded=False means cache hit."""
        p = Path(path)
        if self._remote_host and self._ssh_runner and p.is_file():
            if not self._remote_work_dir:
                remote_username = resolve_remote_username(
                    configured_user=self._remote_user,
                    runner=self._ssh_runner,
                )
                self._remote_work_dir = default_virtuoso_bridge_dir(
                    remote_username, "virtuoso_bridge"
                )
            remote_dir = self._remote_work_dir.rstrip("/")
            remote_path = f"{remote_dir}/{p.name}"
            content = p.read_bytes()
            md5 = hashlib.md5(content).hexdigest()
            cached = self._il_upload_cache.get(str(p))
            if cached and cached[0] == md5:
                return cached[1], False
            up = self._ssh_runner.upload_text(content.decode("utf-8"), remote_path)
            if up.returncode != 0:
                raise RuntimeError(
                    self._ssh_runner.describe_ssh_command_failure(
                        f"upload IL file {p.name}",
                        up,
                    )
                )
            remote_posix = _path_to_posix(remote_path)
            self._il_upload_cache[str(p)] = (md5, remote_posix)
            return remote_posix, True
        return _path_to_posix(p), False

    def _kill_tunnel(self) -> None:
        if self._ssh_tunnel_proc is not None and self._ssh_tunnel_proc.poll() is None:
            logger.info("Terminating SSH tunnel (PID %d)", self._ssh_tunnel_proc.pid)
            self._ssh_tunnel_proc.terminate()
            try:
                self._ssh_tunnel_proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._ssh_tunnel_proc.kill()
            self._ssh_tunnel_proc = None

    @staticmethod
    def _parse_response(raw: str, elapsed: float) -> VirtuosoResult:
        if not raw:
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=["Empty response from daemon"],
                execution_time=elapsed,
            )
        if "TimeoutError" in raw:
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=["SKILL execution timeout in Virtuoso"],
                execution_time=elapsed,
            )
        if raw.startswith(_STX):
            return VirtuosoResult(
                status=ExecutionStatus.SUCCESS,
                output=raw[1:],
                execution_time=elapsed,
            )
        if raw.startswith(_NAK):
            return VirtuosoResult(
                status=ExecutionStatus.ERROR,
                errors=[raw[1:]],
                execution_time=elapsed,
            )
        return VirtuosoResult(
            status=ExecutionStatus.SUCCESS,
            output=raw,
            execution_time=elapsed,
            warnings=["Response did not contain a standard status marker"],
        )
